### ISSUE TITLE
Update to R. 4.3.3

### ISSUE THREAD

**Issue by Claudius-Appel** [Claudius-Appel/duflor#25]
- [x] update to R.4.3.3
- [x] remove RBF from packages
- [x] remove RBF-dependencies from packages
- [ ] update lockfile
- [ ] push and check
